"""title for posts

Revision ID: 16bab3ae886e
Revises: 990eb95516de
Create Date: 2021-05-16 12:39:27.308321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16bab3ae886e'
down_revision = '990eb95516de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=20), nullable=True))
    op.drop_column('post', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img', sa.VARCHAR(length=140), nullable=True))
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
