"""disable img

Revision ID: 990eb95516de
Revises: 591281ded95d
Create Date: 2021-05-15 22:48:53.035967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990eb95516de'
down_revision = '591281ded95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
